name: Article Fetcher
description: Fetch articles from Zenn and Qiita.
author: mk2@mk2.red
inputs:
  zenn:
    description: (JSON Array format) Accounts of Zenn for fetching articles.
  qiita:
    description: (JSON Array format) Accounts of Qiita for fetching articles.
  retentionDays:
    description: retention days
    default: 1
runs:
  using: 'node12'
  main: 'dist/index.js'
